FROM golang:alpine
 
# Deps
RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing --update \
     zlib-dev zlib-static curl-dev curl-static openssl-devopenssl-libs-static \
     alpine-sdk git libtool autoconf automake linux-headers musl-dev m4 build-base perl ca-certificates \
     crypto++-dev crypto++-static brotli-dev brotli-static unzip tar xz wget \
     c-ares-dev c-ares-static sqlite-dev sqlite-static libsodium-dev libsodium-static  nghttp2-dev nghttp2-static
